Better error message when initial/deriv missing dim
Used to print

```
Error: No dim() call found for initial_E
	initial(E[1:N_age]) <- 0 # (line 26)
```

but will now print

```
Error: No dim() call found for E - used in:
	initial(E[1:N_age]) <- 0 # (line 26)
```